/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AdminOrderIndexRouteImport } from './routes/admin-order/index'
import { Route as AdminOrderDangoteRequestFormRouteImport } from './routes/admin-order/dangote-request-form'
import { Route as AdminOrderDepotRouteImport } from './routes/admin-order/depot'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDetailsRouteImport } from './routes/admin/details'
import { Route as AdminFormRouteImport } from './routes/admin/form'
import { Route as AdminUpdateRouteImport } from './routes/admin/update'
import { Route as BankAccountsIndexRouteImport } from './routes/bank-accounts/index'
import { Route as BankAccountsDetailsRouteImport } from './routes/bank-accounts/details'
import { Route as BankAccountsFormRouteImport } from './routes/bank-accounts/form'
import { Route as CommissionsIndexRouteImport } from './routes/commissions/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as CustomersDetailsRouteImport } from './routes/customers/details'
import { Route as CustomersFormRouteImport } from './routes/customers/form'
import { Route as DangoteOrderRequestIndexRouteImport } from './routes/dangote-order-request/index'
import { Route as DangoteOrderRequestReviewRouteImport } from './routes/dangote-order-request/review'
import { Route as DangoteOrdersIndexRouteImport } from './routes/dangote-orders/index'
import { Route as DangoteOrdersDetailsRouteImport } from './routes/dangote-orders/details'
import { Route as DangoteProductsIndexRouteImport } from './routes/dangote-products/index'
import { Route as DangoteProductsDetailsRouteImport } from './routes/dangote-products/details'
import { Route as DangoteProductsFormRouteImport } from './routes/dangote-products/form'
import { Route as DeliveryCustomerIndexRouteImport } from './routes/delivery-customer/index'
import { Route as DeliveryCustomerDetailsRouteImport } from './routes/delivery-customer/details'
import { Route as DeliveryCustomerFormRouteImport } from './routes/delivery-customer/form'
import { Route as DeliveryOperationsIndexRouteImport } from './routes/delivery-operations/index'
import { Route as DeliveryOperationsAllocateTrucksRouteImport } from './routes/delivery-operations/allocate-trucks'
import { Route as DeliveryOperationsAllocationDetailsRouteImport } from './routes/delivery-operations/allocation-details'
import { Route as DeliveryOperationsDetailsRouteImport } from './routes/delivery-operations/details'
import { Route as DepositsIndexRouteImport } from './routes/deposits/index'
import { Route as DepositsDetailsRouteImport } from './routes/deposits/details'
import { Route as DepositsManualDepositRouteImport } from './routes/deposits/manual-deposit'
import { Route as DepotsIndexRouteImport } from './routes/depots/index'
import { Route as DepotsDetailsRouteImport } from './routes/depots/details'
import { Route as DepotsFormRouteImport } from './routes/depots/form'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DriversDetailsRouteImport } from './routes/drivers/details'
import { Route as DriversFormRouteImport } from './routes/drivers/form'
import { Route as FilingStationsIndexRouteImport } from './routes/filing-stations/index'
import { Route as FilingStationsDetailsRouteImport } from './routes/filing-stations/details'
import { Route as FilingStationsFormRouteImport } from './routes/filing-stations/form'
import { Route as LicenceVerificationIndexRouteImport } from './routes/licence-verification/index'
import { Route as LicenceVerificationReviewRouteImport } from './routes/licence-verification/review'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersDetailsRouteImport } from './routes/orders/details'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as PfiIndexRouteImport } from './routes/pfi/index'
import { Route as PfiDetailsRouteImport } from './routes/pfi/details'
import { Route as PfiFormRouteImport } from './routes/pfi/form'
import { Route as ProductPricingIndexRouteImport } from './routes/product-pricing/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsDetailsRouteImport } from './routes/products/details'
import { Route as ProductsFormRouteImport } from './routes/products/form'
import { Route as SalesLedgerIndexRouteImport } from './routes/sales-ledger/index'
import { Route as SalesLedgerAssignCustomerRouteImport } from './routes/sales-ledger/assign-customer'
import { Route as SalesLedgerDetailsRouteImport } from './routes/sales-ledger/details'
import { Route as TicketIndexRouteImport } from './routes/ticket/index'
import { Route as TicketDetailsRouteImport } from './routes/ticket/details'
import { Route as TrucksIndexRouteImport } from './routes/trucks/index'
import { Route as TrucksDetailsRouteImport } from './routes/trucks/details'
import { Route as TrucksFormRouteImport } from './routes/trucks/form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderIndexRoute = AdminOrderIndexRouteImport.update({
  id: '/admin-order/',
  path: '/admin-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderDangoteRequestFormRoute =
  AdminOrderDangoteRequestFormRouteImport.update({
    id: '/admin-order/dangote-request-form',
    path: '/admin-order/dangote-request-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrderDepotRoute = AdminOrderDepotRouteImport.update({
  id: '/admin-order/depot',
  path: '/admin-order/depot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDetailsRoute = AdminDetailsRouteImport.update({
  id: '/admin/details',
  path: '/admin/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormRoute = AdminFormRouteImport.update({
  id: '/admin/form',
  path: '/admin/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdateRoute = AdminUpdateRouteImport.update({
  id: '/admin/update',
  path: '/admin/update',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsIndexRoute = BankAccountsIndexRouteImport.update({
  id: '/bank-accounts/',
  path: '/bank-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsDetailsRoute = BankAccountsDetailsRouteImport.update({
  id: '/bank-accounts/details',
  path: '/bank-accounts/details',
  getParentRoute: () => rootRouteImport,
} as any)
const BankAccountsFormRoute = BankAccountsFormRouteImport.update({
  id: '/bank-accounts/form',
  path: '/bank-accounts/form',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsIndexRoute = CommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersDetailsRoute = CustomersDetailsRouteImport.update({
  id: '/customers/details',
  path: '/customers/details',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersFormRoute = CustomersFormRouteImport.update({
  id: '/customers/form',
  path: '/customers/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteOrderRequestIndexRoute =
  DangoteOrderRequestIndexRouteImport.update({
    id: '/dangote-order-request/',
    path: '/dangote-order-request/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DangoteOrderRequestReviewRoute =
  DangoteOrderRequestReviewRouteImport.update({
    id: '/dangote-order-request/review',
    path: '/dangote-order-request/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const DangoteOrdersIndexRoute = DangoteOrdersIndexRouteImport.update({
  id: '/dangote-orders/',
  path: '/dangote-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteOrdersDetailsRoute = DangoteOrdersDetailsRouteImport.update({
  id: '/dangote-orders/details',
  path: '/dangote-orders/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteProductsIndexRoute = DangoteProductsIndexRouteImport.update({
  id: '/dangote-products/',
  path: '/dangote-products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteProductsDetailsRoute = DangoteProductsDetailsRouteImport.update({
  id: '/dangote-products/details',
  path: '/dangote-products/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DangoteProductsFormRoute = DangoteProductsFormRouteImport.update({
  id: '/dangote-products/form',
  path: '/dangote-products/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerIndexRoute = DeliveryCustomerIndexRouteImport.update({
  id: '/delivery-customer/',
  path: '/delivery-customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerDetailsRoute = DeliveryCustomerDetailsRouteImport.update({
  id: '/delivery-customer/details',
  path: '/delivery-customer/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCustomerFormRoute = DeliveryCustomerFormRouteImport.update({
  id: '/delivery-customer/form',
  path: '/delivery-customer/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOperationsIndexRoute = DeliveryOperationsIndexRouteImport.update({
  id: '/delivery-operations/',
  path: '/delivery-operations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryOperationsAllocateTrucksRoute =
  DeliveryOperationsAllocateTrucksRouteImport.update({
    id: '/delivery-operations/allocate-trucks',
    path: '/delivery-operations/allocate-trucks',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryOperationsAllocationDetailsRoute =
  DeliveryOperationsAllocationDetailsRouteImport.update({
    id: '/delivery-operations/allocation-details',
    path: '/delivery-operations/allocation-details',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeliveryOperationsDetailsRoute =
  DeliveryOperationsDetailsRouteImport.update({
    id: '/delivery-operations/details',
    path: '/delivery-operations/details',
    getParentRoute: () => rootRouteImport,
  } as any)
const DepositsIndexRoute = DepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsDetailsRoute = DepositsDetailsRouteImport.update({
  id: '/deposits/details',
  path: '/deposits/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsManualDepositRoute = DepositsManualDepositRouteImport.update({
  id: '/deposits/manual-deposit',
  path: '/deposits/manual-deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsIndexRoute = DepotsIndexRouteImport.update({
  id: '/depots/',
  path: '/depots/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsDetailsRoute = DepotsDetailsRouteImport.update({
  id: '/depots/details',
  path: '/depots/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DepotsFormRoute = DepotsFormRouteImport.update({
  id: '/depots/form',
  path: '/depots/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDetailsRoute = DriversDetailsRouteImport.update({
  id: '/drivers/details',
  path: '/drivers/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversFormRoute = DriversFormRouteImport.update({
  id: '/drivers/form',
  path: '/drivers/form',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsIndexRoute = FilingStationsIndexRouteImport.update({
  id: '/filing-stations/',
  path: '/filing-stations/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsDetailsRoute = FilingStationsDetailsRouteImport.update({
  id: '/filing-stations/details',
  path: '/filing-stations/details',
  getParentRoute: () => rootRouteImport,
} as any)
const FilingStationsFormRoute = FilingStationsFormRouteImport.update({
  id: '/filing-stations/form',
  path: '/filing-stations/form',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceVerificationIndexRoute =
  LicenceVerificationIndexRouteImport.update({
    id: '/licence-verification/',
    path: '/licence-verification/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LicenceVerificationReviewRoute =
  LicenceVerificationReviewRouteImport.update({
    id: '/licence-verification/review',
    path: '/licence-verification/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersDetailsRoute = OrdersDetailsRouteImport.update({
  id: '/orders/details',
  path: '/orders/details',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiIndexRoute = PfiIndexRouteImport.update({
  id: '/pfi/',
  path: '/pfi/',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiDetailsRoute = PfiDetailsRouteImport.update({
  id: '/pfi/details',
  path: '/pfi/details',
  getParentRoute: () => rootRouteImport,
} as any)
const PfiFormRoute = PfiFormRouteImport.update({
  id: '/pfi/form',
  path: '/pfi/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPricingIndexRoute = ProductPricingIndexRouteImport.update({
  id: '/product-pricing/',
  path: '/product-pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDetailsRoute = ProductsDetailsRouteImport.update({
  id: '/products/details',
  path: '/products/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFormRoute = ProductsFormRouteImport.update({
  id: '/products/form',
  path: '/products/form',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerIndexRoute = SalesLedgerIndexRouteImport.update({
  id: '/sales-ledger/',
  path: '/sales-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLedgerAssignCustomerRoute =
  SalesLedgerAssignCustomerRouteImport.update({
    id: '/sales-ledger/assign-customer',
    path: '/sales-ledger/assign-customer',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalesLedgerDetailsRoute = SalesLedgerDetailsRouteImport.update({
  id: '/sales-ledger/details',
  path: '/sales-ledger/details',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIndexRoute = TicketIndexRouteImport.update({
  id: '/ticket/',
  path: '/ticket/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketDetailsRoute = TicketDetailsRouteImport.update({
  id: '/ticket/details',
  path: '/ticket/details',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksIndexRoute = TrucksIndexRouteImport.update({
  id: '/trucks/',
  path: '/trucks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksDetailsRoute = TrucksDetailsRouteImport.update({
  id: '/trucks/details',
  path: '/trucks/details',
  getParentRoute: () => rootRouteImport,
} as any)
const TrucksFormRoute = TrucksFormRouteImport.update({
  id: '/trucks/form',
  path: '/trucks/form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/trucks/details': typeof TrucksDetailsRoute
  '/trucks/form': typeof TrucksFormRoute
  '/admin-order/': typeof AdminOrderIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bank-accounts/': typeof BankAccountsIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dangote-order-request/': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders/': typeof DangoteOrdersIndexRoute
  '/dangote-products/': typeof DangoteProductsIndexRoute
  '/delivery-customer/': typeof DeliveryCustomerIndexRoute
  '/delivery-operations/': typeof DeliveryOperationsIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/depots/': typeof DepotsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/filing-stations/': typeof FilingStationsIndexRoute
  '/licence-verification/': typeof LicenceVerificationIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/pfi/': typeof PfiIndexRoute
  '/product-pricing/': typeof ProductPricingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales-ledger/': typeof SalesLedgerIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/trucks/details': typeof TrucksDetailsRoute
  '/trucks/form': typeof TrucksFormRoute
  '/admin-order': typeof AdminOrderIndexRoute
  '/admin': typeof AdminIndexRoute
  '/bank-accounts': typeof BankAccountsIndexRoute
  '/commissions': typeof CommissionsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/dangote-order-request': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders': typeof DangoteOrdersIndexRoute
  '/dangote-products': typeof DangoteProductsIndexRoute
  '/delivery-customer': typeof DeliveryCustomerIndexRoute
  '/delivery-operations': typeof DeliveryOperationsIndexRoute
  '/deposits': typeof DepositsIndexRoute
  '/depots': typeof DepotsIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/filing-stations': typeof FilingStationsIndexRoute
  '/licence-verification': typeof LicenceVerificationIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/pfi': typeof PfiIndexRoute
  '/product-pricing': typeof ProductPricingIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales-ledger': typeof SalesLedgerIndexRoute
  '/ticket': typeof TicketIndexRoute
  '/trucks': typeof TrucksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/admin-order/dangote-request-form': typeof AdminOrderDangoteRequestFormRoute
  '/admin-order/depot': typeof AdminOrderDepotRoute
  '/admin/details': typeof AdminDetailsRoute
  '/admin/form': typeof AdminFormRoute
  '/admin/update': typeof AdminUpdateRoute
  '/bank-accounts/details': typeof BankAccountsDetailsRoute
  '/bank-accounts/form': typeof BankAccountsFormRoute
  '/customers/details': typeof CustomersDetailsRoute
  '/customers/form': typeof CustomersFormRoute
  '/dangote-order-request/review': typeof DangoteOrderRequestReviewRoute
  '/dangote-orders/details': typeof DangoteOrdersDetailsRoute
  '/dangote-products/details': typeof DangoteProductsDetailsRoute
  '/dangote-products/form': typeof DangoteProductsFormRoute
  '/delivery-customer/details': typeof DeliveryCustomerDetailsRoute
  '/delivery-customer/form': typeof DeliveryCustomerFormRoute
  '/delivery-operations/allocate-trucks': typeof DeliveryOperationsAllocateTrucksRoute
  '/delivery-operations/allocation-details': typeof DeliveryOperationsAllocationDetailsRoute
  '/delivery-operations/details': typeof DeliveryOperationsDetailsRoute
  '/deposits/details': typeof DepositsDetailsRoute
  '/deposits/manual-deposit': typeof DepositsManualDepositRoute
  '/depots/details': typeof DepotsDetailsRoute
  '/depots/form': typeof DepotsFormRoute
  '/drivers/details': typeof DriversDetailsRoute
  '/drivers/form': typeof DriversFormRoute
  '/filing-stations/details': typeof FilingStationsDetailsRoute
  '/filing-stations/form': typeof FilingStationsFormRoute
  '/licence-verification/review': typeof LicenceVerificationReviewRoute
  '/orders/details': typeof OrdersDetailsRoute
  '/pfi/details': typeof PfiDetailsRoute
  '/pfi/form': typeof PfiFormRoute
  '/products/details': typeof ProductsDetailsRoute
  '/products/form': typeof ProductsFormRoute
  '/sales-ledger/assign-customer': typeof SalesLedgerAssignCustomerRoute
  '/sales-ledger/details': typeof SalesLedgerDetailsRoute
  '/ticket/details': typeof TicketDetailsRoute
  '/trucks/details': typeof TrucksDetailsRoute
  '/trucks/form': typeof TrucksFormRoute
  '/admin-order/': typeof AdminOrderIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bank-accounts/': typeof BankAccountsIndexRoute
  '/commissions/': typeof CommissionsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/dangote-order-request/': typeof DangoteOrderRequestIndexRoute
  '/dangote-orders/': typeof DangoteOrdersIndexRoute
  '/dangote-products/': typeof DangoteProductsIndexRoute
  '/delivery-customer/': typeof DeliveryCustomerIndexRoute
  '/delivery-operations/': typeof DeliveryOperationsIndexRoute
  '/deposits/': typeof DepositsIndexRoute
  '/depots/': typeof DepotsIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/filing-stations/': typeof FilingStationsIndexRoute
  '/licence-verification/': typeof LicenceVerificationIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/pfi/': typeof PfiIndexRoute
  '/product-pricing/': typeof ProductPricingIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales-ledger/': typeof SalesLedgerIndexRoute
  '/ticket/': typeof TicketIndexRoute
  '/trucks/': typeof TrucksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/ticket/details'
    | '/trucks/details'
    | '/trucks/form'
    | '/admin-order/'
    | '/admin/'
    | '/bank-accounts/'
    | '/commissions/'
    | '/customers/'
    | '/dangote-order-request/'
    | '/dangote-orders/'
    | '/dangote-products/'
    | '/delivery-customer/'
    | '/delivery-operations/'
    | '/deposits/'
    | '/depots/'
    | '/drivers/'
    | '/filing-stations/'
    | '/licence-verification/'
    | '/orders/'
    | '/overview/'
    | '/pfi/'
    | '/product-pricing/'
    | '/products/'
    | '/sales-ledger/'
    | '/ticket/'
    | '/trucks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/ticket/details'
    | '/trucks/details'
    | '/trucks/form'
    | '/admin-order'
    | '/admin'
    | '/bank-accounts'
    | '/commissions'
    | '/customers'
    | '/dangote-order-request'
    | '/dangote-orders'
    | '/dangote-products'
    | '/delivery-customer'
    | '/delivery-operations'
    | '/deposits'
    | '/depots'
    | '/drivers'
    | '/filing-stations'
    | '/licence-verification'
    | '/orders'
    | '/overview'
    | '/pfi'
    | '/product-pricing'
    | '/products'
    | '/sales-ledger'
    | '/ticket'
    | '/trucks'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/set-password'
    | '/admin-order/dangote-request-form'
    | '/admin-order/depot'
    | '/admin/details'
    | '/admin/form'
    | '/admin/update'
    | '/bank-accounts/details'
    | '/bank-accounts/form'
    | '/customers/details'
    | '/customers/form'
    | '/dangote-order-request/review'
    | '/dangote-orders/details'
    | '/dangote-products/details'
    | '/dangote-products/form'
    | '/delivery-customer/details'
    | '/delivery-customer/form'
    | '/delivery-operations/allocate-trucks'
    | '/delivery-operations/allocation-details'
    | '/delivery-operations/details'
    | '/deposits/details'
    | '/deposits/manual-deposit'
    | '/depots/details'
    | '/depots/form'
    | '/drivers/details'
    | '/drivers/form'
    | '/filing-stations/details'
    | '/filing-stations/form'
    | '/licence-verification/review'
    | '/orders/details'
    | '/pfi/details'
    | '/pfi/form'
    | '/products/details'
    | '/products/form'
    | '/sales-ledger/assign-customer'
    | '/sales-ledger/details'
    | '/ticket/details'
    | '/trucks/details'
    | '/trucks/form'
    | '/admin-order/'
    | '/admin/'
    | '/bank-accounts/'
    | '/commissions/'
    | '/customers/'
    | '/dangote-order-request/'
    | '/dangote-orders/'
    | '/dangote-products/'
    | '/delivery-customer/'
    | '/delivery-operations/'
    | '/deposits/'
    | '/depots/'
    | '/drivers/'
    | '/filing-stations/'
    | '/licence-verification/'
    | '/orders/'
    | '/overview/'
    | '/pfi/'
    | '/product-pricing/'
    | '/products/'
    | '/sales-ledger/'
    | '/ticket/'
    | '/trucks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  AdminOrderDangoteRequestFormRoute: typeof AdminOrderDangoteRequestFormRoute
  AdminOrderDepotRoute: typeof AdminOrderDepotRoute
  AdminDetailsRoute: typeof AdminDetailsRoute
  AdminFormRoute: typeof AdminFormRoute
  AdminUpdateRoute: typeof AdminUpdateRoute
  BankAccountsDetailsRoute: typeof BankAccountsDetailsRoute
  BankAccountsFormRoute: typeof BankAccountsFormRoute
  CustomersDetailsRoute: typeof CustomersDetailsRoute
  CustomersFormRoute: typeof CustomersFormRoute
  DangoteOrderRequestReviewRoute: typeof DangoteOrderRequestReviewRoute
  DangoteOrdersDetailsRoute: typeof DangoteOrdersDetailsRoute
  DangoteProductsDetailsRoute: typeof DangoteProductsDetailsRoute
  DangoteProductsFormRoute: typeof DangoteProductsFormRoute
  DeliveryCustomerDetailsRoute: typeof DeliveryCustomerDetailsRoute
  DeliveryCustomerFormRoute: typeof DeliveryCustomerFormRoute
  DeliveryOperationsAllocateTrucksRoute: typeof DeliveryOperationsAllocateTrucksRoute
  DeliveryOperationsAllocationDetailsRoute: typeof DeliveryOperationsAllocationDetailsRoute
  DeliveryOperationsDetailsRoute: typeof DeliveryOperationsDetailsRoute
  DepositsDetailsRoute: typeof DepositsDetailsRoute
  DepositsManualDepositRoute: typeof DepositsManualDepositRoute
  DepotsDetailsRoute: typeof DepotsDetailsRoute
  DepotsFormRoute: typeof DepotsFormRoute
  DriversDetailsRoute: typeof DriversDetailsRoute
  DriversFormRoute: typeof DriversFormRoute
  FilingStationsDetailsRoute: typeof FilingStationsDetailsRoute
  FilingStationsFormRoute: typeof FilingStationsFormRoute
  LicenceVerificationReviewRoute: typeof LicenceVerificationReviewRoute
  OrdersDetailsRoute: typeof OrdersDetailsRoute
  PfiDetailsRoute: typeof PfiDetailsRoute
  PfiFormRoute: typeof PfiFormRoute
  ProductsDetailsRoute: typeof ProductsDetailsRoute
  ProductsFormRoute: typeof ProductsFormRoute
  SalesLedgerAssignCustomerRoute: typeof SalesLedgerAssignCustomerRoute
  SalesLedgerDetailsRoute: typeof SalesLedgerDetailsRoute
  TicketDetailsRoute: typeof TicketDetailsRoute
  TrucksDetailsRoute: typeof TrucksDetailsRoute
  TrucksFormRoute: typeof TrucksFormRoute
  AdminOrderIndexRoute: typeof AdminOrderIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BankAccountsIndexRoute: typeof BankAccountsIndexRoute
  CommissionsIndexRoute: typeof CommissionsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DangoteOrderRequestIndexRoute: typeof DangoteOrderRequestIndexRoute
  DangoteOrdersIndexRoute: typeof DangoteOrdersIndexRoute
  DangoteProductsIndexRoute: typeof DangoteProductsIndexRoute
  DeliveryCustomerIndexRoute: typeof DeliveryCustomerIndexRoute
  DeliveryOperationsIndexRoute: typeof DeliveryOperationsIndexRoute
  DepositsIndexRoute: typeof DepositsIndexRoute
  DepotsIndexRoute: typeof DepotsIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  FilingStationsIndexRoute: typeof FilingStationsIndexRoute
  LicenceVerificationIndexRoute: typeof LicenceVerificationIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  PfiIndexRoute: typeof PfiIndexRoute
  ProductPricingIndexRoute: typeof ProductPricingIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SalesLedgerIndexRoute: typeof SalesLedgerIndexRoute
  TicketIndexRoute: typeof TicketIndexRoute
  TrucksIndexRoute: typeof TrucksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/': {
      id: '/admin-order/'
      path: '/admin-order'
      fullPath: '/admin-order/'
      preLoaderRoute: typeof AdminOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/dangote-request-form': {
      id: '/admin-order/dangote-request-form'
      path: '/admin-order/dangote-request-form'
      fullPath: '/admin-order/dangote-request-form'
      preLoaderRoute: typeof AdminOrderDangoteRequestFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-order/depot': {
      id: '/admin-order/depot'
      path: '/admin-order/depot'
      fullPath: '/admin-order/depot'
      preLoaderRoute: typeof AdminOrderDepotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/details': {
      id: '/admin/details'
      path: '/admin/details'
      fullPath: '/admin/details'
      preLoaderRoute: typeof AdminDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/form': {
      id: '/admin/form'
      path: '/admin/form'
      fullPath: '/admin/form'
      preLoaderRoute: typeof AdminFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/update': {
      id: '/admin/update'
      path: '/admin/update'
      fullPath: '/admin/update'
      preLoaderRoute: typeof AdminUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/': {
      id: '/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/bank-accounts/'
      preLoaderRoute: typeof BankAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/details': {
      id: '/bank-accounts/details'
      path: '/bank-accounts/details'
      fullPath: '/bank-accounts/details'
      preLoaderRoute: typeof BankAccountsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-accounts/form': {
      id: '/bank-accounts/form'
      path: '/bank-accounts/form'
      fullPath: '/bank-accounts/form'
      preLoaderRoute: typeof BankAccountsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions/': {
      id: '/commissions/'
      path: '/commissions'
      fullPath: '/commissions/'
      preLoaderRoute: typeof CommissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/details': {
      id: '/customers/details'
      path: '/customers/details'
      fullPath: '/customers/details'
      preLoaderRoute: typeof CustomersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/form': {
      id: '/customers/form'
      path: '/customers/form'
      fullPath: '/customers/form'
      preLoaderRoute: typeof CustomersFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-order-request/': {
      id: '/dangote-order-request/'
      path: '/dangote-order-request'
      fullPath: '/dangote-order-request/'
      preLoaderRoute: typeof DangoteOrderRequestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-order-request/review': {
      id: '/dangote-order-request/review'
      path: '/dangote-order-request/review'
      fullPath: '/dangote-order-request/review'
      preLoaderRoute: typeof DangoteOrderRequestReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-orders/': {
      id: '/dangote-orders/'
      path: '/dangote-orders'
      fullPath: '/dangote-orders/'
      preLoaderRoute: typeof DangoteOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-orders/details': {
      id: '/dangote-orders/details'
      path: '/dangote-orders/details'
      fullPath: '/dangote-orders/details'
      preLoaderRoute: typeof DangoteOrdersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/': {
      id: '/dangote-products/'
      path: '/dangote-products'
      fullPath: '/dangote-products/'
      preLoaderRoute: typeof DangoteProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/details': {
      id: '/dangote-products/details'
      path: '/dangote-products/details'
      fullPath: '/dangote-products/details'
      preLoaderRoute: typeof DangoteProductsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dangote-products/form': {
      id: '/dangote-products/form'
      path: '/dangote-products/form'
      fullPath: '/dangote-products/form'
      preLoaderRoute: typeof DangoteProductsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/': {
      id: '/delivery-customer/'
      path: '/delivery-customer'
      fullPath: '/delivery-customer/'
      preLoaderRoute: typeof DeliveryCustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/details': {
      id: '/delivery-customer/details'
      path: '/delivery-customer/details'
      fullPath: '/delivery-customer/details'
      preLoaderRoute: typeof DeliveryCustomerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-customer/form': {
      id: '/delivery-customer/form'
      path: '/delivery-customer/form'
      fullPath: '/delivery-customer/form'
      preLoaderRoute: typeof DeliveryCustomerFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/': {
      id: '/delivery-operations/'
      path: '/delivery-operations'
      fullPath: '/delivery-operations/'
      preLoaderRoute: typeof DeliveryOperationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/allocate-trucks': {
      id: '/delivery-operations/allocate-trucks'
      path: '/delivery-operations/allocate-trucks'
      fullPath: '/delivery-operations/allocate-trucks'
      preLoaderRoute: typeof DeliveryOperationsAllocateTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/allocation-details': {
      id: '/delivery-operations/allocation-details'
      path: '/delivery-operations/allocation-details'
      fullPath: '/delivery-operations/allocation-details'
      preLoaderRoute: typeof DeliveryOperationsAllocationDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-operations/details': {
      id: '/delivery-operations/details'
      path: '/delivery-operations/details'
      fullPath: '/delivery-operations/details'
      preLoaderRoute: typeof DeliveryOperationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/': {
      id: '/deposits/'
      path: '/deposits'
      fullPath: '/deposits/'
      preLoaderRoute: typeof DepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/details': {
      id: '/deposits/details'
      path: '/deposits/details'
      fullPath: '/deposits/details'
      preLoaderRoute: typeof DepositsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/manual-deposit': {
      id: '/deposits/manual-deposit'
      path: '/deposits/manual-deposit'
      fullPath: '/deposits/manual-deposit'
      preLoaderRoute: typeof DepositsManualDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/': {
      id: '/depots/'
      path: '/depots'
      fullPath: '/depots/'
      preLoaderRoute: typeof DepotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/details': {
      id: '/depots/details'
      path: '/depots/details'
      fullPath: '/depots/details'
      preLoaderRoute: typeof DepotsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depots/form': {
      id: '/depots/form'
      path: '/depots/form'
      fullPath: '/depots/form'
      preLoaderRoute: typeof DepotsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/details': {
      id: '/drivers/details'
      path: '/drivers/details'
      fullPath: '/drivers/details'
      preLoaderRoute: typeof DriversDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/form': {
      id: '/drivers/form'
      path: '/drivers/form'
      fullPath: '/drivers/form'
      preLoaderRoute: typeof DriversFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/': {
      id: '/filing-stations/'
      path: '/filing-stations'
      fullPath: '/filing-stations/'
      preLoaderRoute: typeof FilingStationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/details': {
      id: '/filing-stations/details'
      path: '/filing-stations/details'
      fullPath: '/filing-stations/details'
      preLoaderRoute: typeof FilingStationsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filing-stations/form': {
      id: '/filing-stations/form'
      path: '/filing-stations/form'
      fullPath: '/filing-stations/form'
      preLoaderRoute: typeof FilingStationsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence-verification/': {
      id: '/licence-verification/'
      path: '/licence-verification'
      fullPath: '/licence-verification/'
      preLoaderRoute: typeof LicenceVerificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence-verification/review': {
      id: '/licence-verification/review'
      path: '/licence-verification/review'
      fullPath: '/licence-verification/review'
      preLoaderRoute: typeof LicenceVerificationReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/details': {
      id: '/orders/details'
      path: '/orders/details'
      fullPath: '/orders/details'
      preLoaderRoute: typeof OrdersDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/': {
      id: '/pfi/'
      path: '/pfi'
      fullPath: '/pfi/'
      preLoaderRoute: typeof PfiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/details': {
      id: '/pfi/details'
      path: '/pfi/details'
      fullPath: '/pfi/details'
      preLoaderRoute: typeof PfiDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pfi/form': {
      id: '/pfi/form'
      path: '/pfi/form'
      fullPath: '/pfi/form'
      preLoaderRoute: typeof PfiFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-pricing/': {
      id: '/product-pricing/'
      path: '/product-pricing'
      fullPath: '/product-pricing/'
      preLoaderRoute: typeof ProductPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/details': {
      id: '/products/details'
      path: '/products/details'
      fullPath: '/products/details'
      preLoaderRoute: typeof ProductsDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/form': {
      id: '/products/form'
      path: '/products/form'
      fullPath: '/products/form'
      preLoaderRoute: typeof ProductsFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/': {
      id: '/sales-ledger/'
      path: '/sales-ledger'
      fullPath: '/sales-ledger/'
      preLoaderRoute: typeof SalesLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/assign-customer': {
      id: '/sales-ledger/assign-customer'
      path: '/sales-ledger/assign-customer'
      fullPath: '/sales-ledger/assign-customer'
      preLoaderRoute: typeof SalesLedgerAssignCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-ledger/details': {
      id: '/sales-ledger/details'
      path: '/sales-ledger/details'
      fullPath: '/sales-ledger/details'
      preLoaderRoute: typeof SalesLedgerDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/': {
      id: '/ticket/'
      path: '/ticket'
      fullPath: '/ticket/'
      preLoaderRoute: typeof TicketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/details': {
      id: '/ticket/details'
      path: '/ticket/details'
      fullPath: '/ticket/details'
      preLoaderRoute: typeof TicketDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/': {
      id: '/trucks/'
      path: '/trucks'
      fullPath: '/trucks/'
      preLoaderRoute: typeof TrucksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/details': {
      id: '/trucks/details'
      path: '/trucks/details'
      fullPath: '/trucks/details'
      preLoaderRoute: typeof TrucksDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trucks/form': {
      id: '/trucks/form'
      path: '/trucks/form'
      fullPath: '/trucks/form'
      preLoaderRoute: typeof TrucksFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  AdminOrderDangoteRequestFormRoute: AdminOrderDangoteRequestFormRoute,
  AdminOrderDepotRoute: AdminOrderDepotRoute,
  AdminDetailsRoute: AdminDetailsRoute,
  AdminFormRoute: AdminFormRoute,
  AdminUpdateRoute: AdminUpdateRoute,
  BankAccountsDetailsRoute: BankAccountsDetailsRoute,
  BankAccountsFormRoute: BankAccountsFormRoute,
  CustomersDetailsRoute: CustomersDetailsRoute,
  CustomersFormRoute: CustomersFormRoute,
  DangoteOrderRequestReviewRoute: DangoteOrderRequestReviewRoute,
  DangoteOrdersDetailsRoute: DangoteOrdersDetailsRoute,
  DangoteProductsDetailsRoute: DangoteProductsDetailsRoute,
  DangoteProductsFormRoute: DangoteProductsFormRoute,
  DeliveryCustomerDetailsRoute: DeliveryCustomerDetailsRoute,
  DeliveryCustomerFormRoute: DeliveryCustomerFormRoute,
  DeliveryOperationsAllocateTrucksRoute: DeliveryOperationsAllocateTrucksRoute,
  DeliveryOperationsAllocationDetailsRoute:
    DeliveryOperationsAllocationDetailsRoute,
  DeliveryOperationsDetailsRoute: DeliveryOperationsDetailsRoute,
  DepositsDetailsRoute: DepositsDetailsRoute,
  DepositsManualDepositRoute: DepositsManualDepositRoute,
  DepotsDetailsRoute: DepotsDetailsRoute,
  DepotsFormRoute: DepotsFormRoute,
  DriversDetailsRoute: DriversDetailsRoute,
  DriversFormRoute: DriversFormRoute,
  FilingStationsDetailsRoute: FilingStationsDetailsRoute,
  FilingStationsFormRoute: FilingStationsFormRoute,
  LicenceVerificationReviewRoute: LicenceVerificationReviewRoute,
  OrdersDetailsRoute: OrdersDetailsRoute,
  PfiDetailsRoute: PfiDetailsRoute,
  PfiFormRoute: PfiFormRoute,
  ProductsDetailsRoute: ProductsDetailsRoute,
  ProductsFormRoute: ProductsFormRoute,
  SalesLedgerAssignCustomerRoute: SalesLedgerAssignCustomerRoute,
  SalesLedgerDetailsRoute: SalesLedgerDetailsRoute,
  TicketDetailsRoute: TicketDetailsRoute,
  TrucksDetailsRoute: TrucksDetailsRoute,
  TrucksFormRoute: TrucksFormRoute,
  AdminOrderIndexRoute: AdminOrderIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BankAccountsIndexRoute: BankAccountsIndexRoute,
  CommissionsIndexRoute: CommissionsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DangoteOrderRequestIndexRoute: DangoteOrderRequestIndexRoute,
  DangoteOrdersIndexRoute: DangoteOrdersIndexRoute,
  DangoteProductsIndexRoute: DangoteProductsIndexRoute,
  DeliveryCustomerIndexRoute: DeliveryCustomerIndexRoute,
  DeliveryOperationsIndexRoute: DeliveryOperationsIndexRoute,
  DepositsIndexRoute: DepositsIndexRoute,
  DepotsIndexRoute: DepotsIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  FilingStationsIndexRoute: FilingStationsIndexRoute,
  LicenceVerificationIndexRoute: LicenceVerificationIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  PfiIndexRoute: PfiIndexRoute,
  ProductPricingIndexRoute: ProductPricingIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SalesLedgerIndexRoute: SalesLedgerIndexRoute,
  TicketIndexRoute: TicketIndexRoute,
  TrucksIndexRoute: TrucksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
